image: docker:latest
services:
    - docker:dind

stages:
    - build
    - deploy
variables:
# Common
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
    S3_BUCKET_NAME: $S3_BUCKET_NAME
    CDN_DISTRIBUTION_ID: $CDN_DISTRIBUTION_ID

cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - node_modules/

######################
## BUILD STAGE ##
######################
Build:
    stage: build
    image: node:14
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
        - .next/
        expire_in: 1 day

######################
## DEPLOY STAGE ##
######################
Deploy:
    stage: deploy
    when: manual
    before_script:
        - apk add — no-cache curl jq python py-pip
        - pip install awscli
        - eval $(aws ecr get-login — no-include-email — region $AWS_REGION | sed ‘s|https://||')

    script:
        - aws s3 cp build/ s3://$S3_BUCKET_NAME/ — recursive — include “*”
        - aws cloudfront create-invalidation — distribution-id $CDN_DISTRIBUTION_ID — paths “/*”