service: ${self:custom.name}
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-east-1
plugins: # <- add here
  - serverless-nextjs-plugin
custom:
  name: bustravel-front
  serverless-nextjs: # <- add here
    assetsBucketName: 'bustravel-front-assets-${self:provider.stage}'
package: # <- add here
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
